import { StyleSheet, Platform, Dimensions } from 'react-native';
import { DESIGN } from '../constants/design';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: DESIGN.colors.bgGradient[0],
    },
    starsContainer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        pointerEvents: 'none',
    },
    star: {
        position: 'absolute',
        backgroundColor: '#FFFFFF',
        borderRadius: 2,
        shadowColor: '#FFFFFF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 2,
    },
    specialStar: {
        position: 'absolute',
        backgroundColor: '#FFFFFF',
        borderRadius: 3,
        shadowColor: '#FFFFFF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 1.0,
        shadowRadius: 4,
        elevation: 4,
        // 특별한 별은 더 큰 글로우 효과
    },
    darkContainer: {
        backgroundColor: '#1a1a2e',
    },
    background: {
        flex: 1,
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
    content: {
        flex: 1,
    },
    tabContent: {
        flex: 1,
    },

    // 기본 텍스트 스타일
    defaultText: {
    },

    // 다크모드 공통 스타일
    darkText: {
        color: '#ffffff',
    },
    darkSubText: {
        color: '#cccccc',
    },
    darkCard: {
        backgroundColor: '#3a4556',
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    darkInput: {
        backgroundColor: '#3a4556',
        color: '#ffffff',
        borderColor: '#4a5568',
    },

    // 개선된 고정 CTA
    fixedCTA: {
        marginHorizontal: 20,
        marginTop: Platform.OS === 'ios' ? 70 : 50,
        marginBottom: 16,
        borderRadius: 20,
        overflow: 'hidden',
        shadowColor: '#C9A962',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 15,
    },
    fixedCTAButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
        paddingVertical: 18,
        paddingHorizontal: 24,
    },
    fixedCTAText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '700',
        letterSpacing: -0.3,
    },

    // 개선된 스트릭 배너
    streakBanner: {
        marginHorizontal: 20,
        marginTop: Platform.OS === 'ios' ? 60 : 20,  // iOS에서 노치 영역 피하기 위해 증가
        marginBottom: 0,  // 아래쪽도 완전히 붙이기
        borderRadius: 16,
        overflow: 'hidden',
        shadowColor: '#FFD700',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    streakGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        padding: 16,
    },
    streakText: {
        fontSize: 20,
        fontWeight: '700',
        color: '#fff',
        letterSpacing: -0.3,
    },

    // 헤더 카드 (간격 조정)
    headerCardShadow: {
        marginHorizontal: 20,
        marginBottom: 20,
        marginTop: 0,
        borderRadius: 24,
        ...Platform.select({
            android: {
                elevation: 15,
                backgroundColor: 'transparent',
            },
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 8 },
                shadowOpacity: 0.12,
                shadowRadius: 20,
            },
        }),
    },
    headerCard: {
        borderRadius: 24,
        overflow: 'hidden',
    },
    headerCardWithStreak: {
        borderTopLeftRadius: 0,
        borderTopRightRadius: 0,
    },
    headerGradient: {
        padding: 32,
        alignItems: 'center',
    },
    appTitle: {
        fontSize: 28,
        fontWeight: '800',
        color: '#ffffff',
        marginBottom: 12,
        letterSpacing: -0.8,
    },
    greetingText: {
        fontSize: 16,
        color: 'rgba(255, 255, 255, 0.8)',
        textAlign: 'center',
        lineHeight: 24,
        fontWeight: '500',
        letterSpacing: -0.2,
    },

    // 명언 카드
    quoteCardShadow: {
        marginHorizontal: 20,
        marginBottom: 20,
        borderRadius: 20,
        ...Platform.select({
            android: {
                elevation: 8,
                backgroundColor: 'transparent',
            },
            ios: {
                shadowColor: '#C9A962',
                shadowOffset: { width: 0, height: 4 },
                shadowOpacity: 0.1,
                shadowRadius: 12,
            },
        }),
    },
    quoteCard: {
        borderRadius: 20,
        overflow: 'hidden',
    },
    quoteGradient: {
        padding: 24,
    },
    quoteHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 16,
        gap: 8,
    },
    quoteTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#7dd3fc',
        letterSpacing: -0.3,
    },
    quoteText: {
        fontSize: 16,
        color: 'rgba(255, 255, 255, 0.9)',
        lineHeight: 24,
        fontWeight: '500',
        fontStyle: 'italic',
    },

    // 개선된 트렌드 카드
    trendCard: {
        backgroundColor: '#475569',
        marginHorizontal: 20,
        marginBottom: 20,
        borderRadius: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 8,
    },
    improvedChart: {
        padding: 0,
    },
    chartHeader: {
        marginBottom: 24,
        alignItems: 'center',
    },
    chartTitle: {
        fontSize: 17,
        fontWeight: '700',
        color: '#ffffff',
        marginBottom: 8,
        textAlign: 'center',
        letterSpacing: 0.5,
    },
    chartSubtitle: {
        fontSize: 13,
        color: 'rgba(255, 255, 255, 0.7)',
        fontWeight: '600',
        textAlign: 'center',
        letterSpacing: 0.3,
    },
    chartContent: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        justifyContent: 'space-around',
        height: 50,
    },
    chartPoint: {
        alignItems: 'center',
        flex: 1,
        gap: 8,
    },
    chartBar: {
        width: 12,
        borderRadius: 6,
        minHeight: 8,
    },
    chartLabel: {
        fontSize: 11,
        color: 'rgba(255, 255, 255, 0.6)',
        fontWeight: '600',
        textAlign: 'center',
    },
    emptyChart: {
        padding: 40,
        alignItems: 'center',
    },
    emptyChartText: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.6)',
        textAlign: 'center',
        lineHeight: 20,
    },

    // 스탯 (개선됨)
    statsContainer: {
        width: '85%',
        gap: 20,
    },
    statsHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
        paddingRight: 4,
    },
    statsTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: 'rgba(255, 255, 255, 0.9)',
    },
    helpButton: {
        padding: 4,
        borderRadius: 12,
        backgroundColor: '#3a4556',
    },
    helpBadge: {
        position: 'absolute',
        top: 10,
        left: 30,
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#7dd3fc',
        shadowColor: '#7dd3fc',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.5,
        shadowRadius: 4,
        elevation: 6,
    },
    statRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    statLabel: {
        flex: 0.35,
        fontSize: 18,
        color: 'rgba(255, 255, 255, 0.8)',
        fontWeight: '600',
    },
    statValue: {
        fontSize: 17,
        color: 'rgba(255, 255, 255, 0.6)',
        fontWeight: '700',
        textAlign: 'right',
        flexShrink: 0,
        minWidth: 50,
    },
    // 새로 추가된 statRight 스타일
    statRight: {
        flex: 0.65,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
        gap: 12,
    },
    progressBar: {
        flex: 1,
        height: 10,
        backgroundColor: '#4a5568',
        borderRadius: 5,
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        backgroundColor: '#7dd3fc',
        borderRadius: 5,
    },
    progressFillHappy: {
        height: '100%',
        backgroundColor: '#FFD700',
        borderRadius: 5,
    },

    // 감정 입력 섹션
    emotionSection: {
        backgroundColor: '#475569',
        marginHorizontal: 20,
        marginBottom: 20,
        borderRadius: 24,
        padding: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.1,
        shadowRadius: 16,
        elevation: 12,
    },
    emotionSectionEnhanced: {
        marginHorizontal: 20,
        marginBottom: 20,
        borderRadius: 24,
        shadowColor: '#C9A962',
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.15,
        shadowRadius: 24,
        elevation: 16,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    emotionSectionGradient: {
        padding: 24,
        borderRadius: 24,
    },
    insightCardEnhanced: {
        marginHorizontal: 20,
        marginBottom: 20,
        borderRadius: 24,
        shadowColor: '#4f46e5',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.12,
        shadowRadius: 20,
        elevation: 12,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.18)',
    },
    insightCardGradient: {
        padding: 24,
        borderRadius: 24,
    },

    // 새로운 홈 화면 스타일들
    newHomeContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    newHomeContent: {
        flexGrow: 1,
        paddingHorizontal: 20,
        paddingTop: 8,
        paddingBottom: 120,
        alignItems: 'center',
        width: '100%',
    },
    newHomeHeader: {
        paddingTop: DESIGN.spacing.xxl,
        paddingBottom: DESIGN.spacing.lg,
        alignItems: 'center',
    },
    newHomeGreeting: {
        fontSize: DESIGN.typography.title.size,
        fontWeight: DESIGN.typography.title.weight,
        color: DESIGN.colors.textPrimary,
        textAlign: 'center',
        marginBottom: DESIGN.spacing.sm,
        letterSpacing: DESIGN.typography.title.letterSpacing,
        lineHeight: 42,
    },
    newHomeSubtitle: {
        fontSize: DESIGN.typography.subtitle.size,
        fontWeight: DESIGN.typography.subtitle.weight,
        color: DESIGN.colors.textSecondary,
        textAlign: 'center',
        lineHeight: 26,
        letterSpacing: DESIGN.typography.subtitle.letterSpacing,
    },
    newStreakBanner: {
        marginVertical: 16,
        alignSelf: 'center',
        shadowColor: '#E6C547', // 채도 감소된 색상
        shadowOffset: { width: 0, height: 2 }, // 그림자 강도 감소
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 6,
    },
    newStreakGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 10, // 크기 축소
        borderRadius: 999, // Pill radius
        gap: 8,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.3)',
    },
    newStreakText: {
        color: '#4A5568',
        fontSize: 16,
        fontWeight: '700',
        textShadowColor: 'rgba(255,255,255,0.5)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
    },
    newEmotionWheelSection: {
        marginVertical: 20,
        alignItems: 'center',
    },
    newEmotionWheelSectionMain: {
        marginVertical: 40,
        alignItems: 'center',
        paddingVertical: 30,
    },
    newMainTitle: {
        fontSize: 40,
        fontWeight: '800',
        color: '#ffffff',
        textAlign: 'center',
        marginBottom: 16,
        textShadowColor: 'rgba(0,0,0,0.4)',
        textShadowOffset: { width: 0, height: 3 },
        textShadowRadius: 6,
        letterSpacing: -0.5,
    },
    newSubtitle: {
        fontSize: 18,
        fontWeight: '500',
        color: 'rgba(255,255,255,0.9)',
        textAlign: 'center',
        marginBottom: 32,
        lineHeight: 24,
        paddingHorizontal: 20,
        textShadowColor: 'rgba(0,0,0,0.3)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 3,
    },
    newAIAnalysisSection: {
        marginVertical: 5,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 10,
        paddingHorizontal: 10,
        width: '100%',
    },
    // 서브타이틀 말풍선 - Calm 스타일
    dottedBubble: {
        backgroundColor: DESIGN.colors.cardBg,
        borderRadius: DESIGN.radius.full,
        padding: DESIGN.spacing.md,
        paddingHorizontal: DESIGN.spacing.lg,
        marginBottom: DESIGN.spacing.xl,
        maxWidth: '80%',
        alignSelf: 'center',
        ...DESIGN.shadows.soft,
    },
    dottedBubbleText: {
        color: DESIGN.colors.textSecondary,
        fontSize: DESIGN.typography.body.size,
        lineHeight: DESIGN.typography.body.lineHeight,
        textAlign: 'center',
        fontWeight: '400',
        letterSpacing: 0.1,
    },
    
    // ScrollView의 contentContainerStyle용 중앙 정렬 - 프리미엄 간격
    centeredScrollContent: {
        flexGrow: 1,
        justifyContent: 'center',
        paddingBottom: 120,
    },

    // 중앙 정렬된 메인 컨텐츠 컨테이너 - 프리미엄 간격
    centeredMainContent: {
        paddingHorizontal: 24,
        justifyContent: 'center',
        alignItems: 'center',
        flex: 1,
    },
    submitHelperContainer: {
        marginTop: 12,
        alignItems: 'center',
    },
    submitHelperText: {
        color: 'rgba(255, 255, 255, 0.6)',
        fontSize: 13,
        marginBottom: 8,
    },
    trustBadgeText: {
        color: 'rgba(255, 255, 255, 0.5)',
        fontSize: 12,
    },
    // 새로운 레이아웃 스타일들 - Glassmorphism
    newInputSection: {
        marginVertical: DESIGN.spacing.lg,
        marginBottom: DESIGN.spacing.sm,
        width: '100%',
    },
    newInputCard: {
        backgroundColor: DESIGN.colors.cardBg,
        borderRadius: DESIGN.radius.xl,
        padding: DESIGN.spacing.lg,
        width: '100%',
        alignSelf: 'stretch',
        flexShrink: 0,
        ...DESIGN.shadows.soft,
    },
    // 새로운 입력 컨테이너 스타일 - Glassmorphism
    inputContainer: {
        width: '90%',
        maxWidth: 360,
        alignSelf: 'center',
    },
    // 입력 카드 - Glassmorphism
    inputBubbleOuter: {
        borderRadius: DESIGN.radius.xl,
        backgroundColor: DESIGN.colors.cardBg,
        padding: DESIGN.spacing.lg,
        width: '100%',
        minHeight: 140,
        justifyContent: 'flex-start',
        ...DESIGN.shadows.medium,
    },
    inputCounterRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: DESIGN.spacing.md,
        paddingHorizontal: DESIGN.spacing.sm,
    },
    emotionInputSimple: {
        textAlignVertical: 'top',
        color: DESIGN.colors.textPrimary,
        fontSize: DESIGN.typography.body.size,
        lineHeight: 26,
        paddingVertical: 4,
        paddingHorizontal: 0,
        width: '100%',
        alignSelf: 'stretch',
        fontWeight: '500',
        letterSpacing: 0.3,
        includeFontPadding: false,
    },
    mainCTASection: {
        marginVertical: DESIGN.spacing.xl,
        alignItems: 'center',
        paddingHorizontal: DESIGN.spacing.lg,
    },
    mainCTAButton: {
        width: '65%',
        maxWidth: 240,
    },
    mainCTAButtonLoading: {
        width: '75%',
        maxWidth: 280,
    },
    mainCTAGradient: {
        borderRadius: DESIGN.radius.full,
        paddingVertical: 18,
        paddingHorizontal: 48,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
        ...DESIGN.shadows.medium,
    },
    mainCTAText: {
        color: DESIGN.colors.textOnDark,
        fontSize: DESIGN.typography.button.size,
        fontWeight: DESIGN.typography.button.weight,
        letterSpacing: DESIGN.typography.button.letterSpacing,
    },
    mainCTAHelper: {
        color: DESIGN.colors.textMuted,
        fontSize: DESIGN.typography.caption.size,
        marginTop: DESIGN.spacing.md,
        textAlign: 'center',
        fontWeight: '400',
        letterSpacing: 0.3,
    },
    emptyStateIcon: {
        position: 'absolute',
        top: 20,
        right: 36, // 좌우 패딩 고려한 위치
        zIndex: 0,
    },
    backgroundIcon: {
        opacity: 0.6,
    },
    newAIInputCard: {
        width: '100%',
        padding: 24,
        borderRadius: 24,
        backgroundColor: 'rgba(255, 255, 255, 0.25)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 5,
        borderWidth: 1.5,
        borderColor: 'rgba(255, 255, 255, 0.4)',
    },
    newSectionTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#ffffff',
        textAlign: 'center',
        marginBottom: 20,
        textShadowColor: 'rgba(0,0,0,0.3)',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 4,
    },
    newTrendSection: {
        marginVertical: 40,
        marginTop: 24,
        alignItems: 'center',
        width: '100%',
    },
    newTrendCard: {
        padding: 26,
        borderRadius: 24,
        marginHorizontal: 0,
        width: '88%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 5,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.4)',
    },
    newTrendTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#ffffff',
        textAlign: 'center',
        marginBottom: 15,
        textShadowColor: 'rgba(0,0,0,0.3)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
    },
    newTextInputSection: {
        marginVertical: 20,
        marginHorizontal: 10,
    },
    newTextInputCard: {
        padding: 24,
        borderRadius: 24,
        backgroundColor: 'rgba(255, 255, 255, 0.25)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 5,
        borderWidth: 1.5,
        borderColor: 'rgba(255, 255, 255, 0.4)',
    },
    newTextInputTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#ffffff',
        textAlign: 'center',
        marginBottom: 20,
        textShadowColor: 'rgba(0,0,0,0.3)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#ffffff',
        marginBottom: 24,
        letterSpacing: -0.4,
        textAlign: 'center',
    },
    quickEmotions: {
        marginBottom: 24,
        paddingVertical: 4,
    },
    quickEmotionButton: {
        backgroundColor: '#475569',
        paddingHorizontal: 14,
        paddingVertical: 12,
        borderRadius: 20,
        marginRight: 12,
        alignItems: 'center',
        justifyContent: 'center',
        minWidth: 82,
        width: 82,
        height: 80,
        // 안드로이드에서 중첩된 테두리 문제 해결
        borderWidth: Platform.OS === 'android' ? 1 : 2,
        borderColor: Platform.OS === 'android' ? 'rgba(255, 255, 255, 0.2)' : 'rgba(255, 255, 255, 0.3)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: Platform.OS === 'android' ? 0.02 : 0.05,
        shadowRadius: Platform.OS === 'android' ? 2 : 4,
        elevation: Platform.OS === 'android' ? 1 : 2,
    },
    quickEmotionButtonSelected: {
        backgroundColor: '#3f4f63',
        borderColor: '#7dd3fc',
        shadowColor: '#C9A962',
        shadowOpacity: 0.2,
        elevation: 6,
    },
    quickEmotionButtonWide: {
        width: 92, // 영어일 때 넓게
    },
    quickEmotionEmoji: {
        fontSize: 28,
        marginBottom: 6,
    },
    quickEmotionText: {
        fontSize: 11,
        color: 'rgba(255, 255, 255, 0.8)',
        textAlign: 'center',
        fontWeight: '600',
        letterSpacing: -0.1,
        maxWidth: 70,
        flexShrink: 1,
    },
    quickEmotionTextTight: {
        letterSpacing: -0.1,
    },
    quickEmotionTextSelected: {
        color: '#7dd3fc',
        fontWeight: '700',
    },
    charCount: {
        fontSize: 13,
        color: DESIGN.colors.textMuted,
        textAlign: 'right',
        fontWeight: '400',
    },
    
    // 제출 버튼 (입력창 아래)
    submitButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
        paddingVertical: 18,
        paddingHorizontal: 28,
        borderRadius: 18,
        shadowColor: '#C9A962',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: Platform.OS === 'android' ? 0.2 : 0.35,
        shadowRadius: Platform.OS === 'android' ? 6 : 12,
        elevation: Platform.OS === 'android' ? 8 : 12,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.25)',
    },
    submitButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '700',
        letterSpacing: -0.2,
    },

    // 익명 위로받기
    anonymousCardShadow: {
        marginHorizontal: 20,
        marginBottom: 30,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: 'rgba(102, 126, 234, 0.4)',
        ...Platform.select({
            android: {
                elevation: 12,
                backgroundColor: 'transparent',
            },
            ios: {
                shadowColor: '#C9A962',
                shadowOffset: { width: 0, height: 8 },
                shadowOpacity: 0.15,
                shadowRadius: 20,
            },
        }),
    },
    anonymousCard: {
        borderRadius: 20,
        overflow: 'hidden',
    },
    anonymousButton: {
        minHeight: 72,
    },
    anonymousGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 20,
    },
    anonymousIcon: {
        width: 52,
        height: 52,
        borderRadius: 26,
        backgroundColor: '#3b4261',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 16,
    },
    anonymousContent: {
        flex: 1,
    },
    anonymousTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#ffffff',
        marginBottom: 4,
        letterSpacing: -0.2,
    },
    anonymousDesc: {
        fontSize: 13,
        color: 'rgba(255, 255, 255, 0.8)',
        fontWeight: '500',
    },

    // 탭 헤더
    tabHeader: {
        marginTop: Platform.OS === 'ios' ? 80 : 60,
        marginHorizontal: 20,
        marginBottom: 12,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    tabTitle: {
        fontSize: 40,
        fontWeight: '800',
        color: '#ffffff',
        letterSpacing: -1,
    },

    // 검색
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#475569',
        marginHorizontal: 20,
        marginBottom: 8,
        borderRadius: 16,
        padding: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 4,
    },
    searchInput: {
        flex: 1,
        marginLeft: 12,
        fontSize: 16,
        color: '#ffffff',
        fontWeight: '500',
    },

    // 개선된 필터
    filterContainer: {
        paddingHorizontal: 20,
        marginTop: 8,
        height: 44,
        overflow: 'visible',
    },
    filterChipsContent: {
        alignItems: 'center',
        flexGrow: 0,
    },
    filterChip: {
        backgroundColor: '#475569',
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 20,
        marginRight: 8,
        alignItems: 'center',
        justifyContent: 'center',
        width: 80,
        height: 40,
        flexShrink: 0,
        overflow: 'visible',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    filterChipActive: {
        backgroundColor: '#7dd3fc',
        borderColor: '#7dd3fc',
        shadowColor: '#C9A962',
        shadowOpacity: 0.3,
        elevation: 6,
        height: 44,
        paddingVertical: 12,
    },
    darkFilterChip: {
        backgroundColor: '#3a4556',
    },
    darkFilterChipActive: {
        backgroundColor: '#7dd3fc',
        borderColor: '#7dd3fc',
    },
    filterText: {
        fontSize: 13,
        color: 'rgba(255, 255, 255, 0.8)',
        fontWeight: '600',
        letterSpacing: -0.2,
        textAlign: 'center',
        width: '100%',
    },
    filterTextActive: {
        color: '#fff',
        fontWeight: '700',
    },

    // 빈 상태 (개선됨)
    emptyState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 40,
        paddingHorizontal: 20,
    },
    emptyIcon: {
        fontSize: 72,
        marginBottom: 24,
    },
    emptyText: {
        fontSize: 24,
        color: '#ffffff',
        marginBottom: 32,
        fontWeight: '600',
        letterSpacing: -0.2,
    },
    emptyDesc: {
        fontSize: 14,
        color: 'rgba(74, 55, 40, 0.6)',
        textAlign: 'center',
        lineHeight: 20,
        marginTop: 8,
    },
    emptyStateCTAShadow: {
        borderRadius: 16,
        ...Platform.select({
            android: {
                elevation: 8,
                backgroundColor: 'transparent',
            },
            ios: {
                shadowColor: '#C9A962',
                shadowOffset: { width: 0, height: 4 },
                shadowOpacity: 0.3,
                shadowRadius: 8,
            },
        }),
    },
    emptyStateCTA: {
        borderRadius: 16,
        overflow: 'hidden',
    },
    emptyGradient: {
        paddingHorizontal: 32,
        paddingVertical: 16,
    },
    emptyCTAText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '700',
        letterSpacing: -0.2,
    },

    // 기록 카드 (개선됨)
    historyCardShadow: {
        marginHorizontal: 20,
        marginBottom: 12,
        borderRadius: 20,
        ...Platform.select({
            android: {
                elevation: 6,
                backgroundColor: 'transparent',
            },
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 4 },
                shadowOpacity: 0.08,
                shadowRadius: 12,
            },
        }),
    },
    historyCard: {
        backgroundColor: '#475569',
        borderRadius: 20,
        padding: 20,
        borderLeftWidth: 4,
        borderLeftColor: 'transparent',
        overflow: 'hidden',
    },
    crisisCard: {
        borderLeftColor: '#EF4444',
        borderLeftWidth: 4,
        backgroundColor: '#475569',
    },
    crisisText: {
        color: '#ffffff', // 다른 카드들과 일치하는 흰색 텍스트
    },
    historyHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    historyDate: {
        fontSize: 13,
        color: 'rgba(255, 255, 255, 0.6)',
        fontWeight: '600',
    },
    historyActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    crisisHelper: {
        padding: 4,
    },
    historyText: {
        fontSize: 15,
        color: '#ffffff',
        lineHeight: 22,
        fontWeight: '500',
    },
    quickEmotionDisplay: {
        flexDirection: 'row',
        marginTop: 8,
        alignItems: 'center',
    },
    quickEmotionLabel: {
        fontSize: 13,
        color: 'rgba(255, 255, 255, 0.8)',
        fontWeight: '500',
    },
    quickEmotionValue: {
        fontSize: 13,
        color: '#7dd3fc',
        fontWeight: '700',
    },
    comfortSection: {
        marginTop: 12,
        padding: 12,
        backgroundColor: '#2d4a5a',
        borderRadius: 12,
        borderLeftWidth: 3,
        borderLeftColor: '#7dd3fc',
    },
    comfortTitle: {
        fontSize: 13,
        fontWeight: '700',
        color: '#7dd3fc',
        marginBottom: 4,
    },
    comfortText: {
        fontSize: 13,
        color: '#ffffff',
        lineHeight: 18,
        fontWeight: '500',
    },
    actionSection: {
        marginTop: 8,
        padding: 12,
        backgroundColor: '#4a3d2d',
        borderRadius: 12,
        borderLeftWidth: 3,
        borderLeftColor: '#FFB347',
    },
    actionTitle: {
        fontSize: 13,
        fontWeight: '700',
        color: '#FF8C00',
        marginBottom: 4,
    },
    actionText: {
        fontSize: 13,
        color: '#ffffff',
        lineHeight: 18,
        fontWeight: '500',
    },
    emotionBadge: {
        borderRadius: 12,
        overflow: 'hidden',
    },
    emotionBadgeText: {
        fontSize: 12,
        color: '#7dd3fc',
        fontWeight: '700',
        paddingHorizontal: 12,
        paddingVertical: 6,
        letterSpacing: -0.1,
    },

    // 강도 표시 (새로 추가)
    intensitySection: {
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: 'rgba(0,0,0,0.05)',
    },
    intensityHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    intensityLabel: {
        fontSize: 12,
        color: 'rgba(255, 255, 255, 0.6)',
        fontWeight: '600',
    },
    intensityDots: {
        flexDirection: 'row',
        gap: 3,
    },
    intensityDescription: {
        fontSize: 12,
        color: 'rgba(255, 255, 255, 0.8)',
        fontStyle: 'italic',
        lineHeight: 16,
    },
    intensityDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#5a6578',
    },
    intensityDotActive: {
        backgroundColor: '#7dd3fc',
    },

    // 인사이트 카드 (대폭 개선)
    insightCardShadow: {
        marginHorizontal: 20,
        marginBottom: 20,
        borderRadius: 24,
        ...Platform.select({
            android: {
                elevation: 8,
                backgroundColor: 'transparent',
            },
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 8 },
                shadowOpacity: 0.12,
                shadowRadius: 20,
            },
        }),
    },
    insightCard: {
        backgroundColor: '#475569',
        borderRadius: 24,
        overflow: 'hidden',
    },
    insightTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#ffffff',
        marginBottom: 20,
        letterSpacing: -0.4,
        textAlign: 'center',
    },

    // 핵심 지표 (새로 추가)
    keyMetrics: {
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        alignItems: 'stretch',
        marginBottom: 16,
    },
    metric: {
        flex: 1,
        alignItems: 'center',
        minWidth: 90,
    },
    metricValue: {
        fontSize: 28,
        fontWeight: '800',
        color: '#7dd3fc',
        marginBottom: 4,
    },
    metricLabel: {
        fontSize: 16,
        color: 'rgba(255, 255, 255, 0.8)',
        fontWeight: '600',
        textAlign: 'center',
    },

    // 감정 분포 (개선됨)
    emptyInsight: {
        alignItems: 'center',
        paddingVertical: 32,
    },
    emptyInsightText: {
        fontSize: 20,
        color: 'rgba(255, 255, 255, 0.8)',
        fontWeight: '600',
        textAlign: 'center',
        lineHeight: 28,
    },
    emotionDistribution: {
        gap: 16,
        marginBottom: 20,
    },
    emotionStat: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
    },
    emotionStatLabel: {
        fontSize: 15,
        color: 'rgba(255, 255, 255, 0.8)',
        width: 80,
        fontWeight: '600',
    },
    emotionStatBar: {
        flex: 1,
        height: 8,
        backgroundColor: '#4a5568',
        borderRadius: 4,
        overflow: 'hidden',
    },
    emotionStatFill: {
        height: '100%',
        borderRadius: 4,
    },
    emotionStatCount: {
        fontSize: 13,
        color: 'rgba(255, 255, 255, 0.6)',
        width: 80,
        textAlign: 'right',
        fontWeight: '600',
    },
    insightSummary: {
        paddingTop: 20,
        borderTopWidth: 1,
        borderTopColor: 'rgba(255, 255, 255, 0.3)',
        alignItems: 'center',
        gap: 6,
    },
    insightSummaryText: {
        fontSize: 16,
        color: 'rgba(255, 255, 255, 0.95)',
        marginBottom: 8,
        fontWeight: '700',
        textAlign: 'center',
        letterSpacing: -0.2,
        lineHeight: 22,
    },

    // 나를 살린 문장 (개선됨)
    quoteSectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 16,
        position: 'relative',
    },
    saveButton: {
        position: 'absolute',
        right: 0,
        padding: 8,
        borderRadius: 8,
        backgroundColor: '#3b4261',
    },
    savedQuoteText: {
        fontSize: 18,
        color: '#ffffff',
        lineHeight: 26,
        fontWeight: '500',
        fontStyle: 'italic',
        textAlign: 'center',
        paddingVertical: 16,
    },
    quoteCenterBox: {
        minHeight: 120,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 8,
    },

    // 행동 추천 (새로 추가)
    recommendedActions: {
        gap: 16,
    },
    actionItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
        padding: 16,
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
        borderRadius: 12,
        marginBottom: 8,
    },
    actionIcon: {
        width: 24,
        alignItems: 'center',
    },
    actionText: {
        fontSize: 15,
        color: '#ffffff',
        fontWeight: '500',
        flex: 1,
    },
    checkbox: {
        width: 24,
        height: 24,
        borderRadius: 4,
        borderWidth: 2,
        borderColor: 'rgba(255, 255, 255, 0.4)',
        backgroundColor: 'transparent',
        alignItems: 'center',
        justifyContent: 'center',
    },
    checkboxCompleted: {
        backgroundColor: '#059669',
        borderColor: '#059669',
    },

    // 설정 (대폭 개선)
    settingCardShadow: {
        marginHorizontal: 20,
        marginBottom: 16,
        borderRadius: 20,
        ...Platform.select({
            android: {
                elevation: 8,
                backgroundColor: 'transparent',
            },
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 4 },
                shadowOpacity: 0.08,
                shadowRadius: 12,
            },
        }),
    },
    settingCard: {
        backgroundColor: '#475569',
        borderRadius: 20,
        padding: 20,
        overflow: 'hidden',
    },
    settingCategoryTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#ffffff',
        marginBottom: 20,
        letterSpacing: -0.3,
    },
    settingRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 4,
    },
    settingRowVertical: {
        paddingVertical: 4,
    },
    settingRowButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 12,
    },
    settingInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    settingTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#ffffff',
        letterSpacing: -0.2,
    },
    settingDesc: {
        fontSize: 13,
        color: 'rgba(255, 255, 255, 0.6)',
        marginTop: 2,
        fontWeight: '500',
    },
    settingDivider: {
        height: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.3)',
        marginVertical: 16,
    },

    // 토글 스위치 (개선됨)
    toggleSwitch: {
        width: 56,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#e0e0e0',
        justifyContent: 'center',
        padding: 2,
    },
    toggleSwitchActive: {
        backgroundColor: '#7dd3fc',
    },
    toggleThumb: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#475569',
        alignSelf: 'flex-start',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 4,
    },
    toggleThumbActive: {
        alignSelf: 'flex-end',
    },

    // 언어 옵션 (개선됨)
    languageOptions: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 12,
    },
    languageOption: {
        flex: 1,
        padding: 16,
        borderRadius: 16,
        backgroundColor: 'transparent',
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 8,
        borderWidth: 1,
        borderColor: '#fff',
    },
    activeOption: {
        backgroundColor: 'transparent',
        borderColor: '#FFD700',
    },
    darkLanguageOption: {
        backgroundColor: '#3a4556',
    },
    languageText: {
        fontSize: 15,
        color: 'rgba(255, 255, 255, 0.8)',
        fontWeight: '600',
    },
    activeText: {
        color: '#FFD700',
        fontWeight: '700',
    },

    // 법적 정보 (개선됨)
    legalCard: {
        backgroundColor: 'transparent',
        marginHorizontal: 20,
        marginBottom: 40,
        borderRadius: 20,
        padding: 24,
        alignItems: 'center',
        borderWidth: 1.5,
        borderColor: 'rgba(255, 255, 255, 0.25)',
        width: '90%',
        alignSelf: 'center',
    },
    darkLegalCard: {
        backgroundColor: '#353f50',
    },
    legalText: {
        fontSize: 13,
        color: 'rgba(255, 255, 255, 0.8)',
        textAlign: 'center',
        marginBottom: 20,
        fontWeight: '500',
        lineHeight: 20,
    },
    legalLinks: {
        flexDirection: 'row',
        gap: 24,
        marginBottom: 24,
    },
    linkText: {
        fontSize: 13,
        color: '#7dd3fc',
        textDecorationLine: 'underline',
        fontWeight: '600',
    },
    deleteAccountButton: {
        paddingVertical: 12,
        paddingHorizontal: 24,
    },
    deleteAccountText: {
        fontSize: 13,
        color: '#ffffff',
        fontWeight: '600',
    },

    // 탭 바 (개선됨)
    tabBar: {
        borderTopWidth: 0,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -6 },
        shadowOpacity: 0.12,
        shadowRadius: 16,
        elevation: 25,
    },
    tabGradient: {
        flexDirection: 'row',
        paddingBottom: Platform.OS === 'ios' ? 28 : 12,
        paddingTop: 16,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
    },
    tabItem: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 56,
        paddingVertical: 8,
    },
    tabText: {
        fontSize: 11,
        color: 'rgba(255, 255, 255, 0.9)',
        marginTop: 4,
        fontWeight: '600',
        letterSpacing: -0.1,
        textShadowColor: 'rgba(0, 0, 0, 0.8)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
    },

    // Premium Minimal 탭 바
    tabBarNew: {
        backgroundColor: '#0D1117',
        borderTopWidth: 1,
        borderTopColor: 'rgba(255, 255, 255, 0.04)',
    },
    tabBarInner: {
        flexDirection: 'row',
        paddingBottom: Platform.OS === 'ios' ? 32 : 16,
        paddingTop: 12,
    },
    tabItemNew: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 44,
        paddingVertical: 4,
    },
    tabTextNew: {
        fontSize: 10,
        color: 'rgba(255, 255, 255, 0.3)',
        marginTop: 6,
        fontWeight: '400',
        letterSpacing: 0.5,
    },
    tabTextActive: {
        color: DESIGN.colors.primary,
        fontWeight: '500',
    },

    // 결과 시트 (대폭 개선)
    resultSheet: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -8 },
        shadowOpacity: 0.5,
        shadowRadius: 24,
        elevation: 30,
        overflow: 'hidden',
        backgroundColor: '#161B22',
        borderWidth: 1,
        borderBottomWidth: 0,
        borderColor: 'rgba(255, 255, 255, 0.08)',
    },
    darkSheet: {
        shadowColor: '#fff',
        shadowOpacity: 0.1,
    },
    sheetContainer: {
        flex: 1,
        paddingBottom: Platform.OS === 'ios' ? 40 : 28,
        backgroundColor: '#161B22',
    },
    sheetHandle: {
        width: 48,
        height: 4,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderRadius: 2,
        alignSelf: 'center',
        marginTop: 16,
        marginBottom: 28,
    },
    darkSheetHandle: {
        backgroundColor: '#666',
    },
    sheetContent: {
        paddingHorizontal: 28,
    },
    sheetBadge: {
        backgroundColor: 'rgba(201, 169, 98, 0.15)',
        borderRadius: 24,
        alignSelf: 'flex-start',
        marginBottom: 24,
        borderWidth: 1,
        borderColor: 'rgba(201, 169, 98, 0.3)',
    },
    sheetBadgeText: {
        color: '#C9A962',
        fontSize: 16,
        fontWeight: '600',
        paddingHorizontal: 24,
        paddingVertical: 12,
        letterSpacing: 0.5,
    },
    sheetMessage: {
        fontSize: 20,
        color: '#ffffff',
        lineHeight: 28,
        marginBottom: 20,
        fontWeight: '600',
        letterSpacing: -0.4,
    },

    // 시트 내 강도 표시
    sheetIntensity: {
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderRadius: 16,
        padding: 16,
        marginBottom: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    sheetIntensityTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#fff',
    },

    sheetSection: {
        backgroundColor: 'rgba(255, 255, 255, 0.03)',
        borderRadius: 16,
        padding: 20,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.06)',
    },
    sheetSectionTitle: {
        fontSize: 16,
        fontWeight: '500',
        color: 'rgba(255, 255, 255, 0.9)',
        marginBottom: 12,
        letterSpacing: 0.3,
    },
    sheetSectionText: {
        fontSize: 15,
        color: 'rgba(255, 255, 255, 0.7)',
        lineHeight: 26,
        fontWeight: '400',
    },
    sheetAction: {
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderRadius: 16,
        padding: 20,
        marginBottom: 24,
    },
    darkSheetAction: {
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
    },
    sheetActionTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: '#fff',
        marginBottom: 8,
        letterSpacing: -0.2,
    },
    sheetActionText: {
        fontSize: 15,
        color: 'rgba(255, 255, 255, 0.8)',
        lineHeight: 22,
        fontWeight: '500',
    },

    // 시트 버튼들
    sheetButtons: {
        flexDirection: 'row',
        gap: 12,
    },
    sheetButton: {
        flex: 2,
        borderRadius: 16,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 8,
    },
    sheetButtonSecondary: {
        flex: 1,
        borderRadius: 16,
        paddingVertical: 18,
        backgroundColor: '#475569',
        alignItems: 'center',
        justifyContent: 'center',
    },
    sheetButtonSecondaryText: {
        color: 'rgba(255, 255, 255, 0.8)',
        fontSize: 15,
        fontWeight: '600',
    },
    sheetButtonGradient: {
        padding: 18,
        alignItems: 'center',
        borderRadius: 16,
    },
    sheetButtonText: {
        color: '#0D1117',
        fontSize: 16,
        fontWeight: '600',
        letterSpacing: 0.5,
    },

    // 위기 지원 모달 (대폭 개선)
    crisisOverlay: {
        flex: 1,
        backgroundColor: '#1e293b',
        justifyContent: 'center',
        alignItems: 'center',
    },
    crisisContent: {
        backgroundColor: '#1e293b',
        marginHorizontal: 20,
        borderRadius: 24,
        width: '90%',
        maxWidth: 380,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.25,
        shadowRadius: 16,
        elevation: 0,
    },
    darkCrisisContent: {
        backgroundColor: '#2d3436',
    },
    crisisHeader: {
        alignItems: 'center',
        padding: 28,
        gap: 12,
    },
    crisisTitle: {
        fontSize: 20,
        fontWeight: '800',
        color: '#EF4444',
        textAlign: 'center',
        letterSpacing: -0.3,
    },
    crisisBody: {
        padding: 24,
    },
    crisisMessage: {
        fontSize: 16,
        color: 'rgba(255, 255, 255, 0.8)',
        textAlign: 'center',
        lineHeight: 24,
        marginBottom: 24,
        fontWeight: '500',
    },
    crisisHelplines: {
        gap: 12,
        marginBottom: 20,
    },
    crisisButton: {
        borderRadius: 16,
        overflow: 'hidden',
        shadowColor: '#EF4444',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    crisisButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
        padding: 18,
    },
    crisisButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '700',
    },
    crisisButtonSecondary: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
        backgroundColor: '#FEF2F2',
        borderRadius: 16,
        padding: 18,
        borderWidth: 2,
        borderColor: '#FCA5A5',
    },
    crisisButtonSecondaryText: {
        color: '#EF4444',
        fontSize: 16,
        fontWeight: '600',
    },

    deleteOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    deleteModal: {
        backgroundColor: '#161B22',
        borderRadius: 16,
        padding: 28,
        width: '90%',
        maxWidth: 400,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.5,
        shadowRadius: 20,
        elevation: 0,
    },
    deleteHeader: {
        alignItems: 'center',
        marginBottom: 20,
    },
    deleteTitle: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '600',
        textAlign: 'center',
        marginTop: 12,
    },
    deleteDescription: {
        color: 'rgba(255, 255, 255, 0.5)',
        fontSize: 14,
        textAlign: 'center',
        lineHeight: 22,
        marginBottom: 24,
    },
    nameInput: {
        backgroundColor: 'rgba(255, 255, 255, 0.06)',
        borderRadius: 12,
        paddingVertical: 16,
        paddingHorizontal: 20,
        fontSize: 17,
        color: '#FFFFFF',
        marginBottom: 24,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
        textAlign: 'center',
        fontWeight: '500',
    },
    nameModalEmoji: {
        fontSize: 48,
        marginBottom: 8,
    },
    modalCloseButton: {
        position: 'absolute',
        top: 16,
        right: 16,
        zIndex: 10,
        padding: 4,
        borderRadius: 20,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
    },
    nameConfirmButton: {
        borderRadius: 12,
        overflow: 'hidden',
        alignItems: 'center',
        shadowColor: '#C9A962',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.35,
        shadowRadius: 12,
        elevation: 10,
    },
    nameConfirmGradient: {
        paddingVertical: 16,
        paddingHorizontal: 40,
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
    },
    nameConfirmButtonText: {
        fontSize: 17,
        fontWeight: '600',
        color: '#0D1117',
        letterSpacing: 0.5,
    },
    deleteActionRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 12,
    },
    cancelButton: {
        flex: 1,
        marginRight: 8,
        backgroundColor: 'rgba(255, 255, 255, 0.06)',
        borderRadius: 12,
        paddingVertical: 14,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
        alignItems: 'center',
    },
    cancelButtonText: {
        color: 'rgba(255, 255, 255, 0.8)',
        fontSize: 16,
        fontWeight: '600',
    },
    confirmDeleteButton: {
        flex: 1,
        marginLeft: 8,
        backgroundColor: 'transparent',
        borderRadius: 12,
        paddingVertical: 14,
        alignItems: 'center',
        borderWidth: 0,
        overflow: 'hidden',
    },
    confirmDeleteButtonText: {
        color: '#ffffff',
        fontSize: 16,
        fontWeight: '700',
    },
    crisisDisclaimer: {
        fontSize: 12,
        color: 'rgba(255, 255, 255, 0.6)',
        textAlign: 'center',
        lineHeight: 18,
    },
    crisisCloseButton: {
        backgroundColor: '#475569',
        padding: 20,
        alignItems: 'center',
    },
    crisisCloseText: {
        fontSize: 16,
        color: 'rgba(255, 255, 255, 0.8)',
        fontWeight: '600',
    },

    // 익명 위로 모달 (개선됨)
    modalOverlay: {
        flex: 1,
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContainer: {
        flex: 1,
    },
    modalContent: {
        backgroundColor: 'transparent',
        borderRadius: 24,
        padding: 24,
        width: '90%',
        maxHeight: '80%',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.85)',
        backdropFilter: 'blur(20px)',
        shadowColor: 'rgba(255, 255, 255, 0.3)',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.2,
        shadowRadius: 32,
        elevation: 0,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: Platform.OS === 'ios' ? 60 : 40,
        paddingHorizontal: 20,
        paddingBottom: 20,
        backgroundColor: '#475569',
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    modalTitle: {
        fontSize: 22,
        fontWeight: '700',
        color: '#ffffff',
        letterSpacing: -0.3,
    },
    anonymousInput: {
        backgroundColor: 'transparent',
        borderRadius: 16,
        padding: 20,
        minHeight: 120,
        fontSize: 16,
        textAlignVertical: 'top',
        marginBottom: 20,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.85)',
        backdropFilter: 'blur(20px)',
        color: '#fff', // 입력 텍스트 흰색
    },
    anonymousResult: {
        marginBottom: 20,
        borderRadius: 16,
        overflow: 'hidden',
        shadowColor: '#C9A962',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 4,
    },
    anonymousResultGradient: {
        padding: 20,
    },
    anonymousResultText: {
        fontSize: 16,
        color: '#ffffff',
        lineHeight: 24,
        marginBottom: 12,
        fontWeight: '500',
    },
    anonymousResultAction: {
        fontSize: 14,
        color: '#7dd3fc',
        fontWeight: '600',
    },
    modalSubmitButton: {
        borderRadius: 16,
        overflow: 'hidden',
    },
    modalSubmitButtonDisabled: {
        shadowOpacity: 0,
        elevation: 0,
    },
    gradientButton: {
        paddingHorizontal: 32,
        paddingVertical: 18,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 56,
        flexDirection: 'row',
    },
    modalButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '700',
        letterSpacing: -0.2,
    },

    // 휴지통 모달 (개선됨)
    trashCard: {
        backgroundColor: '#a0aec0',
        marginHorizontal: 20,
        marginTop: 12,
        borderRadius: 12,
        padding: 20,
        shadowColor: '#8b7355',
        shadowOffset: { width: 1, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 6,
        elevation: 3,
        borderWidth: 1,
        borderColor: 'rgba(139, 115, 85, 0.1)',
    },
    trashHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    trashDate: {
        fontSize: 12,
        color: 'rgba(100, 80, 60, 0.7)',
        fontWeight: '600',
    },
    trashEmotion: {
        fontSize: 13,
        color: '#8b4513',
        fontWeight: '700',
        backgroundColor: '#3d342a',
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 8,
    },
    trashText: {
        fontSize: 14,
        color: 'rgba(80, 60, 40, 0.9)',
        marginBottom: 16,
        lineHeight: 20,
    },
    trashActions: {
        flexDirection: 'row',
        gap: 12,
    },
    restoreButton: {
        flex: 1,
        backgroundColor: '#3f4f63',
        borderRadius: 12,
        padding: 12,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 8,
    },
    restoreText: {
        color: '#7dd3fc',
        fontSize: 14,
        fontWeight: '600',
    },
    deleteButton: {
        flex: 1,
        backgroundColor: '#FEF2F2',
        borderRadius: 12,
        padding: 12,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 8,
    },
    deleteText: {
        color: '#EF4444',
        fontSize: 14,
        fontWeight: '600',
    },

    // 토스트 메시지 (새로 추가)
    toast: {
        position: 'absolute',
        top: Platform.OS === 'ios' ? 60 : 40,
        left: 20,
        right: 20,
        borderRadius: 16,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 10,
        zIndex: 1000,
    },
    toastError: {
        shadowColor: '#EF4444',
    },
    toastGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 16,
        gap: 12,
    },
    toastText: {
        fontSize: 14,
        fontWeight: '600',
        textAlign: 'center',
    },
    
    // 앱 잠금 화면 스타일
    lockScreen: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
        backgroundColor: '#0D1117',
    },
    lockIconContainer: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: 'rgba(201, 169, 98, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(201, 169, 98, 0.25)',
        marginBottom: 24,
    },
    lockTitle: {
        fontSize: 22,
        fontWeight: '300',
        color: '#fff',
        marginBottom: 8,
        letterSpacing: 0.5,
    },
    lockDescription: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.5)',
        marginBottom: 40,
        fontWeight: '400',
    },
    unlockButton: {
        marginTop: 20,
        borderRadius: 12,
        overflow: 'hidden',
        shadowColor: '#C9A962',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    lockGradientButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
        paddingHorizontal: 32,
        gap: 10,
    },
    unlockButtonText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#0D1117',
        textAlign: 'center',
    },

    // === 새로 추가 ===
    modalHeaderInline: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        paddingHorizontal: 12,
        backgroundColor: 'transparent',
        borderBottomWidth: 0,
    },
    centeredModalTitle: {
        flex: 1,
        textAlign: 'center',
    },

    charCountContainer: {
        height: 28,                // 공간을 확보해서
        justifyContent: 'center',  // 그 공간의 중앙에 글자 수 배치
        alignItems: 'flex-end',
        marginTop: 8,
        marginBottom: 16,          // 버튼과 적당히 여유 있게
    },
    charCountAnonymous: {
        color: '#999',
    },

    // 의료 면책 조항 스타일
    medicalDisclaimer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#4a2d2d',
        padding: 12,
        borderRadius: 8,
        marginTop: 16,
        gap: 8,
    },
    medicalDisclaimerText: {
        fontSize: 12,
        color: '#EF4444',
        fontWeight: '600',
        flex: 1,
        lineHeight: 16,
    },

    // 다른 위로받기 버튼 스타일
    anotherComfortButton: {
        marginTop: 12,
        alignSelf: 'center',
        paddingVertical: 8,
        paddingHorizontal: 16,
        backgroundColor: '#4a5170',
        borderRadius: 20,
        borderWidth: 1,
        borderColor: 'rgba(102, 126, 234, 0.5)',
    },
    anotherComfortText: {
        color: 'rgba(255, 255, 255, 0.8)',
        fontSize: 14,
        fontWeight: '600',
    },
    
    // 사용량 표시 스타일
    inputInfoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 8,
    },
    dailyUsage: {
        color: DESIGN.colors.textMuted,
        fontSize: 13,
        fontWeight: '400',
    },
    anonymousTitleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    anonymousCount: {
        color: 'rgba(255, 255, 255, 0.8)',
        fontSize: 12,
        fontWeight: '600',
        backgroundColor: '#2d3748',
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 10,
    },
    
    // 비밀번호 모달 스타일
    passwordModalContent: {
        backgroundColor: '#1e293b',
        borderRadius: 20,
        margin: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 0,
    },
    passwordModalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255, 255, 255, 0.1)',
        gap: 8,
    },
    passwordModalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#ffffff',
    },
    passwordModalBody: {
        padding: 20,
        gap: 12,
    },
    passwordModalSubtitle: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.8)',
        textAlign: 'center',
        lineHeight: 20,
    },
    passwordModalWarning: {
        fontSize: 12,
        color: '#F59E0B',
        textAlign: 'center',
        backgroundColor: '#4a3f2a',
        padding: 8,
        borderRadius: 8,
        fontWeight: '500',
    },
    passwordModalInput: {
        backgroundColor: '#475569',
        borderRadius: 12,
        padding: 16,
        fontSize: 16,
        color: '#ffffff',
        textAlign: 'center',
        borderWidth: 2,
        borderColor: 'rgba(74, 222, 128, 0.3)',
        marginTop: 8,
    },
    passwordModalRule: {
        fontSize: 12,
        color: 'rgba(125, 211, 252, 0.8)',
        textAlign: 'center',
        fontStyle: 'italic',
    },
    passwordModalButtons: {
        flexDirection: 'row',
        gap: 12,
        padding: 20,
        paddingTop: 12,
    },
    passwordModalButton: {
        flex: 1,
        borderRadius: 12,
        overflow: 'hidden',
    },
    passwordConfirmGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        gap: 6,
    },
    confirmButtonDisabled: {
        opacity: 0.6,
    },
    // 휴지통 구겨진 종이 효과
    trashModalContainer: {
        backgroundColor: '#f5f0e8', // 구겨진 종이 베이스 색상
        position: 'relative',
    },
    crumpledPaperOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'transparent',
        // 구겨진 종이 텍스처를 그라데이션으로 시뮬레이션
        opacity: 0.15,
        // 여러 겹의 그림자로 구겨진 효과
        shadowColor: '#8b7355',
        shadowOffset: { width: 2, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2,
        // 대각선 패턴 효과
        transform: [{ skewX: '0.5deg' }, { skewY: '0.2deg' }],
    },

    // 주간 감정 카드 스타일
    weeklyEmotionCard: {
        width: '100%',
        marginVertical: 20,
        marginBottom: 24,
    },
    weeklyEmotionGradient: {
        borderRadius: 24,
        padding: 20,
        paddingTop: 16,
        paddingBottom: 16,
        borderWidth: 1.5,
        borderColor: 'rgba(255, 255, 255, 0.4)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 12,
        elevation: 6,
    },
    weeklyEmotionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 12,
    },
    weeklyEmotionTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: '#ffffff',
        letterSpacing: 0.3,
    },
    // 지난 5일 섹션 - Glassmorphism
    recentDaysSection: {
        marginVertical: DESIGN.spacing.lg,
        width: '100%',
        paddingHorizontal: DESIGN.spacing.lg,
    },
    recentDaysCard: {
        borderRadius: DESIGN.radius.xl,
        backgroundColor: DESIGN.colors.cardBg,
        paddingVertical: DESIGN.spacing.lg,
        paddingHorizontal: DESIGN.spacing.xl,
        width: '100%',
        ...DESIGN.shadows.soft,
    },
    recentDaysTitle: {
        fontSize: 18,
        fontWeight: '500',
        color: DESIGN.colors.textPrimary,
        textAlign: 'center',
        marginBottom: DESIGN.spacing.md,
        letterSpacing: 0.2,
    },
    recentDaysList: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        flex: 1,
        gap: DESIGN.spacing.md,
    },
    recentDayItem: {
        alignItems: 'center',
        justifyContent: 'center',
        gap: DESIGN.spacing.xs,
        minWidth: 56,
    },
    recentDayEmoji: {
        fontSize: 24,
    },
    recentDayDate: {
        fontSize: 11,
        color: DESIGN.colors.textMuted,
        fontWeight: '500',
        textAlign: 'center',
    },
    // AI 채팅 스타일
    turnCounter: {
        fontSize: 12,
        color: 'rgba(255, 255, 255, 0.7)',
        marginTop: 4,
    },
    chatHistory: {
        flex: 1,
        marginBottom: 12,
    },
    chatHistoryContent: {
        paddingVertical: 12,
        flexGrow: 1,
    },
    emptyChatContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 60,
    },
    emptyChatText: {
        fontSize: 16,
        color: 'rgba(255, 255, 255, 0.7)',
        textAlign: 'center',
    },
    chatBubble: {
        maxWidth: '75%',
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 18,
        marginVertical: 4,
    },
    chatBubbleUser: {
        alignSelf: 'flex-end',
        backgroundColor: '#06b6d4',
        marginLeft: 60,
    },
    chatBubbleAi: {
        alignSelf: 'flex-start',
        backgroundColor: 'rgba(71, 85, 105, 0.9)',
        marginRight: 60,
    },
    chatBubbleText: {
        fontSize: 15,
        lineHeight: 20,
    },
    chatBubbleTextUser: {
        color: '#ffffff',
    },
    chatBubbleTextAi: {
        color: '#ffffff',
    },
    chatInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    chatInput: {
        flex: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.15)',
        borderRadius: 20,
        paddingHorizontal: 16,
        paddingVertical: 10,
        color: '#ffffff',
        fontSize: 15,
        maxHeight: 100,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.3)',
    },
    chatSendButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#06b6d4',
        alignItems: 'center',
        justifyContent: 'center',
    },
    chatSendButtonDisabled: {
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
    },
    // AI 채팅 전체 화면 스타일
    chatScreenContainer: {
        flex: 1,
        padding: 20,
    },
    chatScreenHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingTop: 24,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255, 255, 255, 0.1)',
        marginBottom: 0,
    },
    chatBackButton: {
        padding: 4,
    },
    chatScreenTitle: {
        fontSize: 20,
        fontWeight: '300',
        color: '#ffffff',
        letterSpacing: 0.5,
    },
    chatScreenSubtitle: {
        fontSize: 13,
        color: 'rgba(255, 255, 255, 0.5)',
        marginTop: 12,
        marginBottom: 8,
        textAlign: 'center',
        fontWeight: '400',
    },
    noTurnsContainer: {
        marginTop: 12,
        marginBottom: 8,
        paddingVertical: 14,
        paddingHorizontal: 20,
        backgroundColor: 'rgba(239, 68, 68, 0.1)',
        borderRadius: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(239, 68, 68, 0.2)',
    },
    noTurnsText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#EF4444',
        textAlign: 'center',
        marginBottom: 4,
    },
    comeBackText: {
        fontSize: 12,
        color: 'rgba(255, 255, 255, 0.5)',
        textAlign: 'center',
    },
    chatScreenHistory: {
        flex: 1,
    },
    chatScreenHistoryContent: {
        paddingVertical: 16,
        flexGrow: 1,
    },
    chatScreenEmpty: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 80,
    },
    chatScreenEmptyText: {
        fontSize: 16,
        color: 'rgba(255, 255, 255, 0.4)',
        textAlign: 'center',
        fontWeight: '400',
    },
    chatScreenBubble: {
        maxWidth: '80%',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 18,
        marginVertical: 6,
    },
    chatScreenBubbleUser: {
        alignSelf: 'flex-end',
        backgroundColor: 'rgba(201, 169, 98, 0.2)',
        borderWidth: 1,
        borderColor: 'rgba(201, 169, 98, 0.3)',
    },
    chatScreenBubbleAi: {
        alignSelf: 'flex-start',
        backgroundColor: 'rgba(255, 255, 255, 0.06)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
    },
    chatScreenBubbleText: {
        fontSize: 15,
        lineHeight: 22,
        fontWeight: '400',
    },
    chatScreenBubbleTextUser: {
        color: '#C9A962',
    },
    chatScreenBubbleTextAi: {
        color: 'rgba(255, 255, 255, 0.9)',
    },
    chatScreenInputContainer: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        gap: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: 'rgba(255, 255, 255, 0.08)',
    },
    chatScreenInput: {
        flex: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.06)',
        borderRadius: 20,
        paddingHorizontal: 18,
        paddingVertical: 12,
        color: '#ffffff',
        fontSize: 15,
        maxHeight: 120,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
    },
    chatScreenSendButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#C9A962',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#C9A962',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    chatScreenSendButtonDisabled: {
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        shadowOpacity: 0,
        elevation: 0,
    },
    // 채팅 기록 모달 스타일 (결과 시트와 동일)
    chatHistoryModalContainer: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-end',
    },
    chatHistoryModalContent: {
        backgroundColor: '#161B22',
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        height: '80%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -8 },
        shadowOpacity: 0.5,
        shadowRadius: 24,
        elevation: 30,
        overflow: 'hidden',
        borderWidth: 1,
        borderBottomWidth: 0,
        borderColor: 'rgba(255, 255, 255, 0.08)',
    },
    chatHistoryBgContainer: {
        flex: 1,
        width: '100%',
        backgroundColor: '#161B22',
        paddingBottom: Platform.OS === 'ios' ? 40 : 28,
    },
    chatHistoryHandle: {
        width: 48,
        height: 4,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderRadius: 2,
        alignSelf: 'center',
        marginTop: 16,
        marginBottom: 20,
    },
    chatHistoryHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 28,
        paddingBottom: 20,
        borderBottomWidth: 0,
    },
    chatHistoryTitle: {
        fontSize: 20,
        fontWeight: '300',
        color: '#ffffff',
        letterSpacing: 0.5,
    },
    chatHistoryCloseButton: {
        padding: 4,
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
        borderRadius: 18,
        width: 36,
        height: 36,
        alignItems: 'center',
        justifyContent: 'center',
    },
    chatHistoryList: {
        paddingHorizontal: 28,
        paddingVertical: 16,
    },
    chatHistoryEmpty: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 60,
    },
    chatHistoryEmptyText: {
        marginTop: 16,
        fontSize: 16,
        color: 'rgba(255, 255, 255, 0.6)',
    },
    chatHistoryItemContainer: {
        marginBottom: 16,
    },
    chatHistoryItem: {
        backgroundColor: 'rgba(255, 255, 255, 0.03)',
        borderRadius: 16,
        padding: 20,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.06)',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    chatHistoryDeleteButton: {
        padding: 8,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    chatHistoryItemTitle: {
        fontSize: 17,
        fontWeight: '700',
        color: '#ffffff',
        lineHeight: 24,
        marginBottom: 8,
        letterSpacing: -0.2,
    },
    chatHistoryItemDate: {
        fontSize: 13,
        color: 'rgba(255, 255, 255, 0.6)',
        fontWeight: '500',
    },
    chatHistoryItemHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    chatHistoryItemCount: {
        fontSize: 12,
        color: 'rgba(255, 255, 255, 0.5)',
    },
    chatHistoryItemPreview: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.7)',
        lineHeight: 20,
    },

    // ============================================
    // DeepLog 홈 화면 스타일
    // ============================================
    deeplogBgLight1: {
        position: 'absolute',
        top: -100,
        right: -50,
        width: 300,
        height: 300,
        borderRadius: 150,
        backgroundColor: 'rgba(100, 150, 180, 0.12)',
    },
    deeplogBgLight2: {
        position: 'absolute',
        bottom: 200,
        left: -100,
        width: 250,
        height: 250,
        borderRadius: 125,
        backgroundColor: 'rgba(100, 150, 180, 0.08)',
    },
    deeplogTitle: {
        fontSize: 28,
        fontWeight: '300',
        color: '#FFFFFF',
        marginTop: 32,
        marginBottom: 32,
        lineHeight: 42,
        textAlign: 'center',
        letterSpacing: 0.3,
    },
    deeplogInputCard: {
        backgroundColor: 'rgba(255, 255, 255, 0.07)',
        borderRadius: 20,
        padding: 24,
        marginBottom: 20,
        minHeight: 140,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
    },
    deeplogTextInput: {
        fontSize: 17,
        color: '#FFFFFF',
        lineHeight: 26,
        minHeight: 100,
        textAlignVertical: 'top',
    },
    deeplogCTAButton: {
        width: '100%',
        borderRadius: 16,
        overflow: 'hidden',
        marginBottom: 20,
    },
    deeplogCTAButtonActive: {
        shadowColor: '#6B9DAD',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.35,
        shadowRadius: 24,
        elevation: 8,
    },
    deeplogCTAGradient: {
        paddingVertical: 18,
        alignItems: 'center',
        justifyContent: 'center',
    },
    deeplogCTAInactive: {
        backgroundColor: 'rgba(255, 255, 255, 0.12)',
        paddingVertical: 18,
        alignItems: 'center',
        justifyContent: 'center',
    },
    deeplogCTAText: {
        fontSize: 17,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    deeplogPrivacyBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        marginBottom: 28,
    },
    deeplogPrivacyText: {
        fontSize: 13,
        color: 'rgba(255, 255, 255, 0.4)',
        fontWeight: '400',
    },
    deeplogStreakCard: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        paddingHorizontal: 20,
        backgroundColor: 'rgba(255, 255, 255, 0.06)',
        borderRadius: 14,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.08)',
    },
    deeplogStreakText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    deeplogStreakSubtext: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.5)',
        fontWeight: '400',
    },
    deeplogRecentSection: {
        marginTop: 0,
    },
    deeplogRecentLabel: {
        fontSize: 12,
        fontWeight: '500',
        color: 'rgba(255, 255, 255, 0.4)',
        marginBottom: 14,
        marginLeft: 4,
        letterSpacing: 0.5,
    },
    deeplogRecentList: {
        flexDirection: 'row',
        gap: 12,
    },
    deeplogRecentItem: {
        flex: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.06)',
        borderRadius: 14,
        paddingVertical: 16,
        paddingHorizontal: 8,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.08)',
    },
    deeplogRecentEmoji: {
        fontSize: 30,
        marginBottom: 8,
    },
    deeplogRecentDay: {
        fontSize: 11,
        color: 'rgba(255, 255, 255, 0.5)',
        fontWeight: '500',
    },
});